apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":"2019-12-02T21:41:18Z","name":"app1","namespace":"default","resourceVersion":"1802","selfLink":"/api/v1/namespaces/default/services/app1","uid":"82d05182-bc31-4373-8e15-50b93a4c69bf"},"spec":{"clusterIP":"10.100.160.220","ports":[{"port":8080,"protocol":"TCP","targetPort":80}],"selector":{"app":"app1"},"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}
  creationTimestamp: '2019-12-02T21:41:18Z'
  name: app1
  namespace: default
  resourceVersion: '16880'
  selfLink: /api/v1/namespaces/default/services/app1
  uid: 82d05182-bc31-4373-8e15-50b93a4c69bf
spec:
  clusterIP: 10.100.160.220
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    app: app1
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
