apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":"2019-12-02T21:45:47Z","name":"app2","namespace":"default","resourceVersion":"1933","selfLink":"/api/v1/namespaces/default/services/app2","uid":"3794002c-dda3-423c-8d80-3d4fc4becc90"},"spec":{"clusterIP":"10.104.246.180","ports":[{"port":8080,"protocol":"TCP","targetPort":80}],"selector":{"app":"app2"},"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}
  creationTimestamp: '2019-12-02T21:45:47Z'
  name: app2
  namespace: default
  resourceVersion: '16882'
  selfLink: /api/v1/namespaces/default/services/app2
  uid: 3794002c-dda3-423c-8d80-3d4fc4becc90
spec:
  clusterIP: 10.104.246.180
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    app: app2
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
