apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    deployment.kubernetes.io/desired-replicas: '1'
    deployment.kubernetes.io/max-replicas: '2'
    deployment.kubernetes.io/revision: '3'
    deployment.kubernetes.io/revision-history: '1'
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"apps/v1","kind":"ReplicaSet","metadata":{"annotations":{"deployment.kubernetes.io/desired-replicas":"1","deployment.kubernetes.io/max-replicas":"2","deployment.kubernetes.io/revision":"3","deployment.kubernetes.io/revision-history":"1"},"creationTimestamp":"2019-12-02T21:41:18Z","generation":2,"labels":{"app":"app1","pod-template-hash":"5569b5bb59"},"name":"app1-5569b5bb59","namespace":"default","ownerReferences":[{"apiVersion":"apps/v1","blockOwnerDeletion":true,"controller":true,"kind":"Deployment","name":"app1","uid":"1b57807e-80ec-4698-a5ff-0d9f0bb6a1e4"}],"resourceVersion":"2233","selfLink":"/apis/apps/v1/namespaces/default/replicasets/app1-5569b5bb59","uid":"5ab352cb-a4ef-4f34-84fd-ea48c13bd128"},"spec":{"replicas":0,"selector":{"matchLabels":{"app":"app1","pod-template-hash":"5569b5bb59"}},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"app1","pod-template-hash":"5569b5bb59"}},"spec":{"containers":[{"image":"nginx:1.7.9","imagePullPolicy":"IfNotPresent","name":"nginx","ports":[{"containerPort":8080,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"observedGeneration":2,"replicas":0}}
  creationTimestamp: '2019-12-02T21:41:18Z'
  generation: 2
  labels:
    app: app1
    pod-template-hash: 5569b5bb59
  name: app1-5569b5bb59
  namespace: default
  ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: app1
      uid: 1b57807e-80ec-4698-a5ff-0d9f0bb6a1e4
  resourceVersion: '16891'
  selfLink: /apis/apps/v1/namespaces/default/replicasets/app1-5569b5bb59
  uid: 5ab352cb-a4ef-4f34-84fd-ea48c13bd128
spec:
  replicas: 0
  selector:
    matchLabels:
      app: app1
      pod-template-hash: 5569b5bb59
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app1
        pod-template-hash: 5569b5bb59
    spec:
      containers:
        - image: 'nginx:1.7.9'
          imagePullPolicy: IfNotPresent
          name: nginx
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  observedGeneration: 2
  replicas: 0
