apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    deployment.kubernetes.io/desired-replicas: '1'
    deployment.kubernetes.io/max-replicas: '2'
    deployment.kubernetes.io/revision: '4'
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"apps/v1","kind":"ReplicaSet","metadata":{"annotations":{"deployment.kubernetes.io/desired-replicas":"1","deployment.kubernetes.io/max-replicas":"2","deployment.kubernetes.io/revision":"4"},"creationTimestamp":"2019-12-02T21:48:19Z","generation":1,"labels":{"app":"app1","pod-template-hash":"ffcd69dbb"},"name":"app1-ffcd69dbb","namespace":"default","ownerReferences":[{"apiVersion":"apps/v1","blockOwnerDeletion":true,"controller":true,"kind":"Deployment","name":"app1","uid":"1b57807e-80ec-4698-a5ff-0d9f0bb6a1e4"}],"resourceVersion":"6110","selfLink":"/apis/apps/v1/namespaces/default/replicasets/app1-ffcd69dbb","uid":"48e467b4-ca85-4952-8229-057c789e745d"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"app1","pod-template-hash":"ffcd69dbb"}},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"app1","pod-template-hash":"ffcd69dbb"}},"spec":{"containers":[{"image":"nginx:1.7","imagePullPolicy":"IfNotPresent","name":"nginx","ports":[{"containerPort":8080,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":1,"fullyLabeledReplicas":1,"observedGeneration":1,"readyReplicas":1,"replicas":1}}
  creationTimestamp: '2019-12-02T21:48:19Z'
  generation: 1
  labels:
    app: app1
    pod-template-hash: ffcd69dbb
  name: app1-ffcd69dbb
  namespace: default
  ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: app1
      uid: 1b57807e-80ec-4698-a5ff-0d9f0bb6a1e4
  resourceVersion: '16894'
  selfLink: /apis/apps/v1/namespaces/default/replicasets/app1-ffcd69dbb
  uid: 48e467b4-ca85-4952-8229-057c789e745d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
      pod-template-hash: ffcd69dbb
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app1
        pod-template-hash: ffcd69dbb
    spec:
      containers:
        - image: 'nginx:1.7'
          imagePullPolicy: IfNotPresent
          name: nginx
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  fullyLabeledReplicas: 1
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
