apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: '2020-01-18T12:42:04Z'
  generateName: nginx-deployment-54f57cf6bf-
  labels:
    app: nginx
    pod-template-hash: 54f57cf6bf
  name: nginx-deployment-54f57cf6bf-ds9rq
  namespace: default
  ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: nginx-deployment-54f57cf6bf
      uid: 84069de9-ee50-4506-8cbe-ff0b6b5ce3e7
  resourceVersion: '19529'
  selfLink: /api/v1/namespaces/default/pods/nginx-deployment-54f57cf6bf-ds9rq
  uid: 0af4c87e-9ae2-4a68-8977-bb91cd6ef8a0
spec:
  containers:
    - image: 'nginx:1.7.9'
      imagePullPolicy: IfNotPresent
      name: nginx
      ports:
        - containerPort: 80
          protocol: TCP
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: default-token-gxpwh
          readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
  volumes:
    - name: default-token-gxpwh
      secret:
        defaultMode: 420
        secretName: default-token-gxpwh
status:
  conditions:
    - lastProbeTime: null
      lastTransitionTime: '2020-01-18T12:42:05Z'
      status: 'True'
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: '2020-01-18T12:42:06Z'
      status: 'True'
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: '2020-01-18T12:42:06Z'
      status: 'True'
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: '2020-01-18T12:42:04Z'
      status: 'True'
      type: PodScheduled
  containerStatuses:
    - containerID: >-
        docker://0cfd9004e76cee8f185fa7c7b9f3e4086cfb7eb8e3c40ae174a976adc21becc4
      image: 'nginx:1.7.9'
      imageID: >-
        docker-pullable://nginx@sha256:e3456c851a152494c3e4ff5fcc26f240206abac0c9d794affb40e0714846c451
      lastState: {}
      name: nginx
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: '2020-01-18T12:42:06Z'
  hostIP: 192.168.64.2
  phase: Running
  podIP: 172.17.0.6
  podIPs:
    - ip: 172.17.0.6
  qosClass: BestEffort
  startTime: '2020-01-18T12:42:05Z'
